name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # -----------------------------------------------
      # PASO A: Gitleaks Scan (Pre-commit check)
      # -----------------------------------------------
      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          report: gitleaks-results.json
          exit-code: 1

      # -----------------------------------------------
      # PASO B: Trivy FS Scan (Vulnerabilidades en dependencias)
      # Escanea el código fuente y dependencias (requirements.txt)
      # -----------------------------------------------
      - name: Trivy FS Scan (Dependencias)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          input: '.' 
          # Mantenemos 'ignore-unfixed: true' aquí también para consistencia
          ignore-unfixed: true 
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1' 

      # -----------------------------------------------
      # PASO C: Construir la Imagen Docker
      # -----------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image (Force no-cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: devsecops-app:latest
          load: true 
          no-cache: true 

      # -----------------------------------------------
      # PASO D: Trivy Image Scan (Post-Build Check)
      # IGNORA LAS VULNERABILIDADES SIN PARCHE DISPONIBLE
      # -----------------------------------------------
      - name: Run Trivy vulnerability scanner on Docker image (Ignorando Unfixed)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-app:latest'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'
          vuln-type: 'os,library'
          # ESTE ES EL CAMBIO CLAVE: Ignorar vulnerabilidades sin parche.
          ignore-unfixed: true 

      - name: Pipeline Success
        if: success()
        run: echo "¡Pipeline DevSecOps COMPLETADO EXITOSAMENTE! (Imagen escaneada)"